server:
  port: 8081
spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.jdbc.Driver

    #url: jdbc:mysql://127.0.0.1:3306/helloword?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://silverhi.asuscomm.com:9529/helloword?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    #password: 123456
    password: molei8686138110
    dbcp2:
      min-idle: 5
      max-total: 5
      max-wait-millis: 150
mybatis:
  mapper-locations: classpath*:com.silver.helloword/**/dao/mapper/*.xml